= "plugin.xml" expression injection
Andrey Hihlovskiy
2014-06-28
:sectanchors:
:jbake-type: page
:jbake-status: published

We already programmed xref:Plugin.xml-for-eclipse-ide-app#["plugin.xml" for IDE app]. Now we can how to do "plugin.xml" expression injection.

Let's take an link:../tree/master/examples/PluginXml-1.html[example Eclipse plugin] we created in xref:plugin.xml-for-eclipse-bundle#["plugin.xml" for Eclipse bundle].

Edit the file "tutorials/MyEclipsePlugin/src/main/resources/plugin.xml", change content to:

```xml
<plugin>
  <extension point="org.eclipse.ui.views">
    <view id="myviewid" name="${project.ext.myViewName}" class="myeclipseplugin.MyView"/>
  </extension>
</plugin>
```

Edit the file "tutorials/MyEclipsePlugin/build.gradle", insert code:

```groovy
wuff {
  filterPluginXml = true
}

ext {
  myViewName = 'test123'
}
```

Invoke on command line: `gradle build`.

Open file "tutorials/MyBuildPlugin/build/libs/MyBuildPlugin-1.0.0.0.jar", open "plugin.xml", it should contain:

```xml
<plugin>
  <extension point="org.eclipse.ui.views">
    <view id="myviewid" name="test123" class="myeclipseplugin.MyView"/>
  </extension>
</plugin>
```

Note that expressions in "plugin.xml" are **not** expanded by default. We must set wuff.filterPluginXml=true to enable this feature.

Note that sometimes dollar sign, **$**, is used for Eclipse-specific expressions in "plugin.xml". Typical example is localized location of intro pages: 

```xml
<extension point="org.eclipse.ui.intro.config">
  <config id="MyRcpApp.introConfigId" introId="MyRcpApp.intro" content="$nl$/intro/introContent.xml">
    <presentation home-page-id="homePageId" standby-page-id="homePageId">
      <implementation kind="html"/>
    </presentation>
  </config>
</extension>
```

Expression injection would produce errors with such Eclipse-specific expressions, because dollar sign has special meaning to it (see more information at link:http://groovy.codehaus.org/Groovy+Templates.html[Groovy templates documentation]). To avoid the errors, we need to escape dollar sign:

```xml
<extension point="org.eclipse.ui.intro.config">
  <config id="MyRcpApp.introConfigId" introId="MyRcpApp.intro" content="\$nl\$/intro/introContent.xml">
    <presentation home-page-id="homePageId" standby-page-id="homePageId">
      <implementation kind="html"/>
    </presentation>
  </config>
</extension>
```

---

The example code for this page: link:../tree/master/examples/PluginXml-4.html[examples/PluginXml-4].

We are done with programming "plugin.xml". Now we can go back to xref:index#[documentation home page] and learn something else.
